### ISSUE TITLE
tour: [APENAS CORREÇÕES ORTOGRÁFICAS]

### ISSUE THREAD

**Issue by willyangcaetano** [golangbr/go-tour-br#10]
Contexto: https://go-tour-br.appspot.com/moretypes/7

Olá ! Vi alguns pequenos erros ortográficos, e gostaria de contribuir, posso !?

No texto abaixo, encontrei os seguintes erros:

> Uma matriz tem um tamanho fixo. Uma slice, por outro lado, é dinâmicamente redimencionada, uma visão flexível dos elementos de uma matriz. Na prática, as slices são muito mais comuns do que as matrizes.
> 
> O tipo []T é uma slice com elementos do tipo T.
> 
> Essa expressão cria uma slice dos primeiros cinco elementos do array a:

Correção ortográfica:
dinâmicamente = dinamicamente
redimencionada = redimensionada

Gostaria também, com base no texto original, que suponho ser esse:
https://go-tour-br.appspot.com/moretypes/7

Fazer as seguintes mudanças em relação as frases iniciais:

"Uma matriz tem um tamanho fixo. Um slice, por outro lado, é redimensionável dinamicamente, uma visão flexível dos elementos de uma matriz."....

Espero estar contribuindo.
Desde já, agradeço

**Comment by dgv** [comment]
https://github.com/golangbr/go-tour-br/commit/4d8ca846074e04d7a0af128b468325cd2cd19ebe sim, obrigado, desculpe a demora :wink:
