### ISSUE TITLE
Possível erro de digitação

### ISSUE THREAD

**Issue by WhoisBsa** [golangbr/go-tour-br#23]
Contexto: https://go-tour-br.appspot.com/methods/13

Chamar um método em uma interface **nila** resulta em um erro de tempo de execução porq

O correto seria _em uma interface **nula** resulta..._

**Comment by gerep** [comment]
Olá @WhoisBsa, você pode enviar um PR com a correção?

**Comment by WhoisBsa** [comment]
Posso sim :)

Aguarde um momento

Em Seg, 27 de mai de 2019 15:27, Gerep <notifications@github.com> escreveu:
