### ISSUE TITLE
tour: Erro no texto

### ISSUE THREAD

**Issue by yuriolive** [golangbr/go-tour-br#8]
Contexto: https://go-tour-br.appspot.com/methods/9

O texto está escrito: **Observe: Tem um erro no _exemple_ na linha 22.** , deveria ser exemplo e não exemple

**Comment by dgv** [comment]
https://github.com/golangbr/go-tour-br/commit/fb80d1cd7359ac3f37b6a5b6ba1b47a7e7f95816
